### ISSUE TITLE
 NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

### ISSUE THREAD

**Issue by javatutorials2016** [hrueger/nativescript-letter-avatar#47]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.
ERROR in node_modules/nativescript-letter-avatar/angular/letter-avatar.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (nativescript-letter-avatar/angular) which declares LetterAvatarModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

1 export declare class LetterAvatarModule {
### Which platform(s) does your issue occur on?
- iOS/Android/Both  IOS
- iOS/Android versions 
- emulator or device. What type of device? EMULATOR when trying to run tns run ios

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)
7.0.10

- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
 "@angular/animations": "^10.1.5",
    "@angular/common": "~10.0.9",
    "@angular/compiler": "~10.0.9",
    "@angular/core": "~10.0.9",
    "@angular/forms": "~10.0.9",
    "@angular/localize": "~10.0.9",
    "@angular/platform-browser": "~10.0.9",
    "@angular/platform-browser-dynamic": "~10.0.9",
    "@angular/router": "~10.0.9",
    "@angular/service-worker": "~10.0.9",
    "@nativescript/angular": "~10.1.0",
    "@nativescript/core": "~7.0.0",
    "@nativescript/theme": "~2.5.0",
    "@ng-bootstrap/ng-bootstrap": "^7.0.0",
    "@stomp/ng2-stompjs": "^7.2.0",
    "@types/node-rsa": "^1.0.0",
    "@types/socket.io-client": "^1.4.33",
    "aes-js": "^3.1.2",
    "angularx-social-login": "^3.2.1",
    "bootstrap": "^4.5.0",
    "constants": "0.0.2",
    "core-js": "^3.6.5",
    "cryptico": "^1.0.2",
    "crypto": "^1.0.1",
    "crypto-module": "^1.3.19",
    "event-source-polyfill": "^1.0.16",
    "idb": "^5.0.4",
    "mediasoup-client": "^3.6.12",
    "moment": "^2.27.0",
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

**Comment by hrueger** [comment]
Hi @javatutorials2016,
This plugin does not support NativeScript 7 yet but I'm working on it.
Once done, the plugin will be moved to [`@schoolsquirrel/letter-avatar`](https://github.com/SchoolSquirrel/nativescript-plugins) because I'm using the new NativeScript Plugin Seed which itself uses a monorepo.

**Comment by hrueger** [comment]
Hi @javatutorials2016,
Updating the plugin was easier than I had expected. Please try the new version: [`@schoolsquirrel/letter-avatar`](https://www.npmjs.com/package/@schoolsquirrel/letter-avatar)
The API is the same, you only have to replace `nativescript-letter-avatar` with `@schoolsquirrel/letter-avatar`.

**Comment by javatutorials2016** [comment]
thanks it worked, used your sample  code in the main page <LetterAvatar text="AB"></LetterAvatar> . Maybe
![Screen Shot 2020-10-18 at 11 51 41 AM](https://user-images.githubusercontent.com/19355588/96373151-94f72e00-1138-11eb-8eb6-9c66698441e9.png)
 I need to do some styling as AVATAR took entire width.

**Comment by hrueger** [comment]
@javatutorials2016 Great! I suggest using a `GridLayout`.
If you have any other problems, feel free to open an issue in the https://github.com/SchoolSquirrel/nativescript-plugins repository as I'll archive this one now.
