### ISSUE TITLE
Android app crashes if I set fontSize attribute on the component

### ISSUE THREAD

**Issue by phaeton2040** [hrueger/nativescript-letter-avatar#9]
Examples work fine however, if I try to set fontSize on the LetterAvatar component the app crashes with the following error

System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method getView failed
System.err: TypeError: Cannot read property 'get' of undefined
System.err: 
System.err: StackTrace:
System.err: setLocalValue(file:///node_modules/@nativescript/core/ui/core/properties/properties.js:426:0)
System.err:     at push.../node_modules/@nativescript/angular/view-util.js.ViewUtil.setPropertyInternal(file:///node_modules/@nativescript/angular/view-util.js:290:0)
System.err:     at push.../node_modules/@nativescript/angular/view-util.js.ViewUtil.setProperty(file:///node_modules/@nativescript/angular/view-util.js:263:0)

**Comment by hrueger** [comment]
I've released v0.3.0, can you upgrade and check if this resolves your problem?

**Comment by phaeton2040** [comment]
Confirm fontSize working in new release. An example in docs works as intended
